#!/bin/bash

REPO_DEPENDENCIES=(
    "the-lodash"
    "the-logger"
    "the-promise"
    "@kubevious/entity-meta"
    "@kubevious/helpers"
    "@kubevious/easy-data-store"
    "@kubevious/helper-backend"
    "@kubevious/helper-logic-processor"
    "@kubevious/helper-rule-engine"
    "@kubevious/worldvious-client"
    "@kubevious/data-models"
    "@kubevious/ui-middleware"
    "@kubevious/http-client"
    "@kubevious/helper-redis"
    "@kubevious/agent-middleware"
)

FORCE_RESOLVE_DEPENDENCIES=(
    "the-lodash"
    "the-logger"
    "the-promise"
    "@kubevious/entity-meta"
    "@kubevious/helpers"
    "@kubevious/easy-data-store"
    "@kubevious/helper-backend"
    "@kubevious/helper-logic-processor"
    "@kubevious/helper-rule-engine"
    "@kubevious/worldvious-client"
    "@kubevious/data-models"
    "@kubevious/ui-middleware"
    "@kubevious/http-client"
    "@kubevious/helper-redis"
    "@kubevious/agent-middleware"
)
